language: node_js
sudo: false
node_js:
- 4
- 6
- stable
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_320e4a7e27b3_key -iv $encrypted_320e4a7e27b3_iv -in auth.js.enc -out test/resources/auth.js -d ||
  true'
- npm install -g typescript
script:
- tsc
#- npm run test-travis
- mocha test/integration/test.visual_recognition.js -g 'authentication'
- sh scripts/typedoc/generate_typedoc.sh
after_success:
- npm run report-coverage
- scripts/jsdoc/publish.sh
